baseURL = "https://5pages.netlify.app/"
languageCode = "en-us"
title = "5 Pages A Day"
description = "Daily I read five pages from various books and provide my thoughts on the subject"
theme = "yinyang"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true

[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = "date"
weight = 100
[[related.indices]]
name = "keywords"
weight = 100

[author]
  name = "Narendra Mandadapu"
  shortname = "Narendra"
  homepage = "https://twitter.com/scriptstar/"

[params]
mainSections = ["books"]
description = "Daily I read five pages from various books and provide my thoughts on the subject"
tagline = "i READ 5 pages DAILY and share my thoughts"
extraHead = ''
amaDisclaimer = "As an Amazon Associate I earn from qualifying purchases"
lazyImage = true
headTitle = "5 Pages A Day"
#postFooterContent = '<br/><br/><form method="post" action="https://sendfox.com/form/1v6nzm/m8ny9r" class="sendfox-form" id="m8ny9r" data-async="true"><p><input type="email" placeholder="Email" name="email" required /></p><!-- no botz please --><div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="a_password" tabindex="-1" value="" autocomplete="off" /></div><p><button type="submit">Get My Thoughts</button></p></form><script src="https://sendfox.com/js/form.js"></script>'
postFooterContent = '<br/><br/><div><a href="https://sendfox.com/naren" target="_blank" rel="noopener">Subscribe to my thoughts</a></div>'
postHeaderContent = '<div><a href="https://sendfox.com/naren" target="_blank" rel="noopener">Subscribe to my thoughts</a></div>'

[[params.headerPage]]
name = "Start here"
link = "start"

[[params.socials]]
name = "Who Am I?"
link = "http://twitter.com/scriptstar"

[[params.socials]]
name = "Subscribe"
link = "https://sendfox.com/naren"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[markup]
  defaultMarkdownHandler = "blackfriday"